/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import cache.Linea;
import configuraciones.EspecificacionCache;
import configuraciones.EspecificacionRam;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 * Consultar los componentes y sus contenidos en las difirentes posiciones.
 * @author Marvin
 */
public class Componentes extends javax.swing.JPanel {

    private EspecificacionCache especificaCache;
    private EspecificacionRam especificaRam;
    
    /**
     * Creates new form Componentes
     */
    public Componentes() {
        initComponents();
    }
    
    public void aplicarEspecificacionCache(){
        TableColumnModel columnaModel = new DefaultTableColumnModel();
        int totalColumnas = especificaCache.getRam().getTamañoBloque() + 1;
        DefaultTableModel tablaCache = (DefaultTableModel) tlbCACHE.getModel();
        for (int i = tablaCache.getRowCount() - 1; i >= 0; i--) {
            tablaCache.removeRow(i);
        }
        tablaCache.setColumnCount(totalColumnas);
        
        for(int i = 0; i < totalColumnas; i++){
            TableColumn columna = new TableColumn(i);
            if(i == 0)
                columna.setHeaderValue("Linea");
            else
                columna.setHeaderValue(i - 1);
            columnaModel.addColumn(columna);
        }
        tlbCACHE.setColumnModel(columnaModel);
        
        for(int i = 0; i < Home.CACHE.size(); i++){
            Linea l = Home.CACHE.get(i);
            Object[] a1 = new Object[1];
            a1[0] = String.valueOf(i);
            Object[] ret = new Object[a1.length + l.elementos.size()];
            System.arraycopy(a1, 0, ret, 0, a1.length);
            System.arraycopy(l.elementos.toArray(), 0, ret, a1.length, l.elementos.size());
            tablaCache.addRow(ret);
        }
    }
    
    public void aplicarEspecificacionRam(){
        DefaultTableModel tablaRam = (DefaultTableModel) tlbRAM.getModel();
        for (int i = tablaRam.getRowCount() - 1; i >= 0; i--) {
            tablaRam.removeRow(i);
        }
        tablaRam.setColumnCount(2);
        tablaRam.setColumnIdentifiers(new Object[]{"Direcciones", "Datos"});
        for(int i = 0; i < Home.RAM.size(); i++){
            tablaRam.addRow(new Object[]{Integer.toHexString(i), Home.RAM.get(i)});
        }
    }

    public EspecificacionCache getEspecificaCache() {
        return especificaCache;
    }

    public void setEspecificaCache(EspecificacionCache especificaCache) {
        this.especificaCache = especificaCache;
    }

    public EspecificacionRam getEspecificaRam() {
        return especificaRam;
    }

    public void setEspecificaRam(EspecificacionRam especificaRam) {
        this.especificaRam = especificaRam;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbCACHE = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tlbRAM = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Contenido de los componentes especificados (Cache y RAM).");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cache"));

        tlbCACHE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tlbCACHE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("RAM"));

        tlbRAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tlbRAM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tlbCACHE;
    private javax.swing.JTable tlbRAM;
    // End of variables declaration//GEN-END:variables
}
